language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - MOODLE_BRANCH=MOODLE_26_STABLE DB=mysqli
  - MOODLE_BRANCH=MOODLE_27_STABLE DB=mysqli
  - MOODLE_BRANCH=MOODLE_28_STABLE DB=mysqli
  - MOODLE_BRANCH=MOODLE_29_STABLE DB=mysqli
  - MOODLE_BRANCH=MOODLE_30_STABLE DB=mysqli
  - MOODLE_BRANCH=MOODLE_26_STABLE DB=pgsql
  - MOODLE_BRANCH=MOODLE_27_STABLE DB=pgsql
  - MOODLE_BRANCH=MOODLE_28_STABLE DB=pgsql
  - MOODLE_BRANCH=MOODLE_29_STABLE DB=pgsql
  - MOODLE_BRANCH=MOODLE_30_STABLE DB=pgsql

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_30_STABLE DB=pgsql
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_30_STABLE DB=mysqli

before_install:
  - phpenv config-rm xdebug.ini
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - export TRAVIS_BUILD_DIR="/home/travis/build/talis/aspire-moodle-integration/2.x-activity-module/mod/aspirelists"
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  #- moodle-plugin-ci codechecker
  - moodle-plugin-ci csslint
  - moodle-plugin-ci shifter
  #- moodle-plugin-ci jshint
  - moodle-plugin-ci validate
  - moodle-plugin-ci phpunit
  #- moodle-plugin-ci behat